"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

from plistlib import Plist
plist = Plist.fromFile('Info.plist')
plist.update({'CFBundleDisplayName': 'Minecraft Portable-wx', 'CFBundleExecutable': 'Minecraft Portable-wx', 'CFBundleName': 'Minecraft Portable-wx'})

APP = ['minecraftp-wx.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False, 'plist': plist, 'iconfile': 'Icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
